server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false
spring.profiles.active=local

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.adverto.dejonghe.application,dev.hilla,com.flowingcode
spring.jpa.defer-datasource-initialization = true

spring.mongodb.authentication-database=admin
spring.mongodb.database=dejonghe
spring.mongodb.uri=mongodb://DejongheTechniek:Yngwie1983_Biprom@localhost:27017/admin
#spring.mongodb.uri=mongodb://DejongheTechniek:Yngwie1983_Biprom@192.168.1.90:27017/admin

spring.main.allow-circular-references = true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

billit.api.key=2810da0e-fddc-4999-af51-ef43150da9c2
billit.party.id=37730554

app.update.folder.local=C:\\dejonghe\\update-tablet-local
app.update.folder.remote=C:\\dejonghe\\update-tablet-remote

rootTemplateProforma = C:\\dejonghe\\templates\\proforma.jrxml
#rootTemplateProforma = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/proforma.jrxml

rootTemplateInvoice = C:\\dejonghe\\templates\\factuur.jrxml
#rootTemplateInvoice = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/factuur.jrxml

rootTemplateQuote = C:\\dejonghe\\templates\\offerte.jrxml
#rootTemplateQuote = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/offerte.jrxml

rootTemplateCreditNote = C:\\dejonghe\\templates\\creditNota.jrxml
#rootTemplateCreditNote = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/creditNota.jrxml

rootTemplateAttachement = C:\\dejonghe\\templates\\bijlage.jrxml
#rootTemplateAttachement = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/bijlage.jrxml

linkSpreadsheetBulk = D:\\Algemeen\\Documentatie\\Dejonghe-techniek\\Database\\dejonghe.xlsx
#linkSpreadsheetBulk = /Users/bramvandenberghe/Desktop/dejonghe.xlsx

rootFolder = C:\\dejonghe\\
#rootFolder = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/

rootTemplateWorkorder = C:\\dejonghe\\templates\\workorder.jrxml
#rootTemplateWorkorder = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/workorder.jrxml

rootTemplateCollectOrder = C:\\dejonghe\\templates\\collectorder.jrxml
#rootTemplateCollectOrder = /Users/bramvandenberghe/Documents/Documenten - MacBook Pro van Bram/Biprom/Biprom Software/Klanten/dejonghe/collectorder.jrxml

tablet.local.latest-version=1.0.1
tablet.external.latest-version=1.0.1